AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hackathon starter template with Node.js and Python examples

Metadata:
  esbuild-properties: &esbuild-properties
    Format: esm
    Minify: false
    OutExtension:
      - .js=.mjs
    Target: es2020
    Sourcemap: false
    EntryPoints:
      - index.mjs
    Banner:
      - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
    External:
      - "@aws-sdk/*"
    Loader: []

Globals:
  Function:
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        TABLE_NAME: !Ref DataTable

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - '*'

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  GetResourceBFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - get.mjs
    Properties:
      Runtime: nodejs22.x
      Handler: get.handler
      CodeUri: functions/resourceTypeB/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !GetAtt DataTable.Arn
      Events:
        GetApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resourceB
            Method: get

  CreateResourceBFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - create.mjs
    Properties:
      Runtime: nodejs22.x
      Handler: create.handler
      CodeUri: functions/resourceTypeB/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt DataTable.Arn
      Events:
        PostApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resourceB
            Method: post

  GetResourceAFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      Handler: get.lambda_handler
      CodeUri: functions/resourceTypeA/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !GetAtt DataTable.Arn
      Events:
        GetApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resourceA
            Method: get

  CreateResourceAFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      Handler: create.lambda_handler
      CodeUri: functions/resourceTypeA/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt DataTable.Arn
      Events:
        PostApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resourceA
            Method: post

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  TableName:
    Description: DynamoDB table name
    Value: !Ref DataTable
